#!/usr/bin/python3

#---------README---------
#searches for ping logs, *.log file, ping logs with time stamps generated by relevant batch file
#outputs *.csv file (error time, successive error count)
#input file name is used as output file name, extension changed
#emrea, Apr 2022

import os

#filter for "ping*.log"
infile_prefix = "ping"
infile_ext = ".log" #iperf results txt
outfile_ext = ".csv"
ping_error_time = "timed" #Request timed out.
ping_error_dest = "unreachable" #Destination host unreachable.
sep = "-" #seperator for time stamp and prints

dirPath = os.path.dirname(os.path.realpath(__file__))


for fileName in os.listdir(dirPath):
    if fileName.endswith(infile_ext) and fileName.startswith(infile_prefix):
        print("Parsing file: %s" % fileName)
        ping_response=[]
        ping_timestamp=[]
        file = open(os.path.join(dirPath,fileName), 'r')
        for line in file:
            ping_timestamp.append(line.split(sep)[0])
            if (ping_error_time in line) or (ping_error_dest in line): #timed out or dest unreachable
                ping_response.append(1)
            else:
                ping_response.append(0) #successful ping
        file.close()
        
        #print(ping_response)
        #print(ping_timestamp)
        
        #find successive error indexes and its time
        i = 0
        index = []
        count = []
        while i <len(ping_response):
            successive_count = 0
            while ping_response[i]:
                i+=1
                successive_count += 1
            if successive_count != 0:
                index.append(i-successive_count)
                count.append(successive_count)
            i += 1
            
        #print(index)
        #print(count)

        outfname = fileName.replace(infile_ext, outfile_ext)
        file = open(os.path.join(dirPath,outfname), 'w')
        file.write("Ping error time;successive count\n")
        for i in range(len(index)):
            file.write("%s;%s\n" %(ping_timestamp[index[i]],count[i]))
        file.close()